---
backendType: marathon
endpoint: http://10.10.0.1:8080,10.0.0.2:8080,10.0.0.3:8080
fluentdEnabled: true
debugEnabled: true
oauth2Enabled: true
AuthorizationType: 0
tlsCertfilePath: /path/to/your/certfile
tlsKeyfilePath: /path/to/your/keyfile
logFlushInterval: 5 #in seconds
port: 8082
MarathonAuth:
  enabled: true
  MarathonHttpUser: MARATHON_USER
  MarathonHttpPassword: MARATHON_PASSWORD
AuthorizedTeams:
  - Realm: teams
    Uid: tm 
    Cn: Platform Engineering / System
EndpointPattern: https://%s.lb.zalando.net
